package com.llp.model;

import lombok.Data;

@Data
public class CreateSessionRequest {

    private String name;
    private String ownerName;
    private int sessionParticipants;

    // Constructors, getters, and setters are automatically generated by Lombok's @Data
}
