package com.llp.model;

import lombok.Data;

@Data
public class LoginRequest {

    private String username;
    private String password;

    // Constructors, getters, and setters are automatically generated by Lombok's @Data
}
