package com.llp.model;

import lombok.Data;

@Data
public class RestaurantSubmission {

    private int sessionId;
    private String restaurantName;
    private String userName;

    // Constructors, getters, and setters are automatically generated by Lombok's @Data
}
